### ISSUE TITLE
Can't connect to mysql from report-server

### ISSUE THREAD

**Issue by iamakimmer** [bitnami/bitnami-docker-reportserver#5]
Just taking from [raw docker-compose](https://github.com/bitnami/bitnami-docker-reportserver/blob/master/docker-compose.yml)
```
version: '2'

services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - MARIADB_USER=bn_reportserver
      - MARIADB_DATABASE=bitnami_reportserver
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  reportserver:
    image: 'docker.io/bitnami/reportserver:3-debian-10'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - REPORTSERVER_DATABASE_USER=bn_reportserver
      - REPORTSERVER_DATABASE_NAME=bitnami_reportserver
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:8080'
      - '443:8443'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
```

This is the output:

```reportserver_1  | nami    INFO  Initializing mysql-client
reportserver_1  | nami    INFO  mysql-client successfully initialized
reportserver_1  | nami    INFO  Initializing reportserver
reportserver_1  | reports INFO  Preparing ReportServer environment...
reportserver_1  | mysql-c INFO  Trying to connect to MySQL server
reportserver_1  | mysql-c INFO  Found MySQL server listening at mariadb:3306
reportserver_1  | mysql-c INFO  MySQL server listening and working at mariadb:3306
reportserver_1  | reports INFO  Creating database schema
reportserver_1  | reports INFO  Configuring ReportServer settings...
reportserver_1  | reports INFO  Deploying in tomcat
reportserver_1  | reports INFO  Creating rsinit file
reportserver_1  | reports INFO  Starting tomcat
reportserver_1  | reports INFO  Waiting for the database tables to be populated
mariadb_1       | 2020-10-03 14:59:41 23 [Warning] Aborted connection 23 to db: 'bitnami_reportserver' user: 'bn_reportserver' host: '172.24.0.3' (Got an error reading communication packets)
reportserver_1  | reports INFO  Configuring user credentials...
reportserver_1  | reports INFO 
reportserver_1  | reports INFO  ########################################################################
reportserver_1  | reports INFO   Installation parameters for reportserver:
reportserver_1  | reports INFO     Site URL: 172.24.0.3:8080
reportserver_1  | reports INFO   This installation requires no credentials.
reportserver_1  | reports INFO  ########################################################################
reportserver_1  | reports INFO 
reportserver_1  | nami    INFO  reportserver successfully initialized
reportserver_1  | INFO  ==> Starting gosu... 
reportserver_1  | 
reportserver_1  | Application Server: Apache Tomcat/9.0.38
reportserver_1  | 
reportserver_1  | ### PAM Configuration ###
reportserver_1  | Static PAM configuration: net.datenwerke.rs.authenticator.service.pam.UserPasswordPAMAuthoritative
reportserver_1  | Finalized PAM configuration: class net.datenwerke.rs.authenticator.service.pam.UserPasswordPAMAuthoritative
reportserver_1  | 
reportserver_1  | 
reportserver_1  | 15:00:05.045 INFO  n.d.r.s.s.search.SearchServiceImpl - Rebuilding search index...
reportserver_1  | 15:00:05.324 INFO  n.d.g.s.lateinit.LateInitStartup - Startup completed
```
and I can't seem to get to the page, getting this:

mariadb_1       | 2020-10-03 14:59:41 23 [Warning] Aborted connection 23 to db: 'bitnami_reportserver' user: 'bn_reportserver' host: '172.24.0.3' (Got an error reading communication packets)

If I ssh into the report-server container, can't connect to MySQL directly:

```
 mattkimoldmac@matthews-MacBook-Pro  ~  docker exec -it 902d6d1c15e8dfea279798d50336f3b1270020b4085e49cf5eac9d57256a70e9 /bin/sh; exit
# mysql  
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/opt/bitnami/mysql/tmp/mysql.sock' (2)
# 
```

If I ssh into the MySQL container, I can connect:

```
 mattkimoldmac@matthews-MacBook-Pro  ~  docker exec -it 0511765bae8a73bdd6d5941c4326a480d5e75d94d33200574b13a9aae4f25a5c /bin/sh; exit
$ mysql -u root
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 51
Server version: 10.3.24-MariaDB Source distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> 




```

Would love to get some advice! Thank you!
