### ISSUE TITLE
Can't view details in Teamspace reports

### ISSUE THREAD

**Issue by kferrone** [bitnami/bitnami-docker-reportserver#6]
**Description**

In the teamspace section I am unable to view any of the details tabs when selecting anything. 

**Steps to reproduce the issue:**

1. got to teamspace section
2. select report
3. see big java error in details

**Describe the results you received:**

```
HTTP Status 500 – Internal Server Error
Type Exception Report

Message java.lang.NullPointerException

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

java.lang.IllegalStateException: java.lang.NullPointerException
	net.datenwerke.rs.reportdoc.service.ReportDocumentationServiceImpl.getCompiledDocumentation(ReportDocumentationServiceImpl.java:225)
	net.datenwerke.rs.reportdoc.service.ReportDocumentationServiceImpl.executeDocumentation(ReportDocumentationServiceImpl.java:80)
	net.datenwerke.rs.reportdoc.server.ReportDocumentationServlet.getDocumentation(ReportDocumentationServlet.java:269)
	net.datenwerke.rs.reportdoc.server.ReportDocumentationServlet.doGet(ReportDocumentationServlet.java:91)
	net.datenwerke.security.service.security.aop.SecurityCheckInterceptor.invoke(SecurityCheckInterceptor.java:109)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	net.datenwerke.security.service.security.aop.SecurityCheckInterceptor.invoke(SecurityCheckInterceptor.java:109)
	com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
	com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
	com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
	com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
	com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:94)
	com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
	com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
Root Cause

java.lang.NullPointerException
	java.base/java.io.Reader.<init>(Reader.java:167)
	java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:109)
	org.apache.commons.io.IOUtils.copy(IOUtils.java:921)
	org.apache.commons.io.IOUtils.toString(IOUtils.java:2681)
	org.apache.commons.io.IOUtils.toString(IOUtils.java:2661)
	net.datenwerke.rs.reportdoc.service.ReportDocumentationServiceImpl.compile(ReportDocumentationServiceImpl.java:274)
	net.datenwerke.rs.reportdoc.service.ReportDocumentationServiceImpl.getCompiledDocumentation(ReportDocumentationServiceImpl.java:222)
	net.datenwerke.rs.reportdoc.service.ReportDocumentationServiceImpl.executeDocumentation(ReportDocumentationServiceImpl.java:80)
	net.datenwerke.rs.reportdoc.server.ReportDocumentationServlet.getDocumentation(ReportDocumentationServlet.java:269)
	net.datenwerke.rs.reportdoc.server.ReportDocumentationServlet.doGet(ReportDocumentationServlet.java:91)
	net.datenwerke.security.service.security.aop.SecurityCheckInterceptor.invoke(SecurityCheckInterceptor.java:109)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	net.datenwerke.security.service.security.aop.SecurityCheckInterceptor.invoke(SecurityCheckInterceptor.java:109)
	com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
	com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
	com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
	com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
	com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:94)
	com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
	com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
Note The full stack trace of the root cause is available in the server logs.

Apache Tomcat/9.0.45
```

**Describe the results you expected:**

show me the details

**Additional information you deem important (e.g. issue happens only occasionally):**

Using the latest version of Docker in EKS.

**Comment by javsalgar** [comment]
Hi,

I'm not a ReportServer expert but I would like to reproduce the issue.

![image](https://user-images.githubusercontent.com/1133777/116853824-f70c1200-abf6-11eb-9832-75d012c94eab.png)


How should I add a Report that triggers the issue?

**Comment by kferrone** [comment]
I didn't add anything. The issue is all reports and I'm just using the auto generated test/demo data which comes with ReportServer, ie I set `REPORTSERVER_INSTALLDEMODATA` to `yes`. I have installed on EKS with the following manifests below. 
<img width="1907" alt="Screen Shot 2021-05-03 at 1 11 30 PM" src="https://user-images.githubusercontent.com/4399427/116921440-38112000-ac11-11eb-9a86-9b736790e396.png">

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportserver
spec:
  selector:
    matchLabels:
      app: reportserver
  template:
    metadata:
      labels:
        app: reportserver
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: reportserver
      containers:
      - name: reportserver
        image: docker.io/bitnami/reportserver:latest
        resources:
          limits: {}
            # memory: "128Mi"
            # cpu: "500m"
        env:
          - name: MARIADB_HOST
            value: mariadb
          - name: MARIADB_PORT_NUMBER
            value: "3306"
          - name: REPORTSERVER_DATABASE_NAME
            value: reportserver
          - name: REPORTSERVER_DATABASE_USER
            value: reportserver
          - name: REPORTSERVER_DATABASE_PASSWORD
            value: password
          - name: REPORTSERVER_USERNAME
            value: admin
          - name: REPORTSERVER_PASSWORD
            value: password
          - name: REPORTSERVER_EMAIL
            value: me@mail.com
          - name: REPORTSERVER_INSTALLDEMODATA
            value: "yes"
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: https
        volumeMounts:
          - name: data
            mountPath: /bitnami
---
apiVersion: v1
kind: Service
metadata:
  name: reportserver
spec:
  selector:
    app: reportserver
  ports:
  - port: 8080
    name: http
    targetPort: http
  - port: 8443
    name: https
    targetPort: https
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: reportserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: reportserver
  annotations:
    external-dns.alpha.kubernetes.io/alias: 'true'
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: reports.mydomain.com
      http:
        paths:
          - path: /
            backend:
              serviceName: reportserver
              servicePort: http
          - path: /*
            backend:
              serviceName: reportserver
              servicePort: http

```
