### ISSUE TITLE
Setting up SMTP datasink  fails

### ISSUE THREAD

**Issue by DarkAxi0m** [bitnami/bitnami-docker-reportserver#7]
**Description**

Testing any SMTP datasink fails

**Steps to reproduce the issue:**

1. Create SMTP DataSink, using correct settings or not
2. Push Test Datasink

**The datasink test failed.**
> Unable to provision, see the following errors: 1) null returned by binding at net.datenwerke.rs.core.service.mail.MailModule.provideDefaultFrom() but the 3rd parameter of net.datenwerke.rs.core.service.mail.SimpleCryptoMail.<init>(SimpleCryptoMail.java:70) is not @Nullable at net.datenwerke.rs.core.service.mail.MailModule.provideDefaultFrom(MailModule.java:186) at net.datenwerke.rs.core.service.mail.MailModule.provideDefaultFrom(MailModule.java:186) while locating java.lang.String annotated with @net.datenwerke.rs.core.service.mail.annotations.MailModuleDefaultFrom() for the 3rd parameter of net.datenwerke.rs.core.service.mail.SimpleCryptoMail.<init>(SimpleCryptoMail.java:70) while locating net.datenwerke.rs.core.service.mail.SimpleCryptoMail annotated with @com.google.inject.internal.UniqueAnnotations$Internal(value=1) 1 error
> display error details
> 

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:
```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 12:00:56 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

- Output of `docker info`:

```
docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.3)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 72
  Running: 9
  Paused: 0
  Stopped: 63
 Images: 887
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.104-microsoft-standard
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 12.42GiB
 Name: docker-desktop
 ID: CE5Q:6OD7:INA6:JNFL:67J6:4HIC:B5JR:GXOS:VO3M:TUIO:CH77:4HII
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 114
  Goroutines: 117
  System Time: 2021-06-22T07:58:05.1542327Z
  EventsListeners: 4
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020

```

docker-compose.yaml
```
version: "3"

services:
  rsmariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - MARIADB_USER=bn_reportserver
      - MARIADB_DATABASE=bitnami_reportserver
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  reportserver:
    image: docker.io/bitnami/reportserver:latest
    environment:
      - MARIADB_HOST=rsmariadb
      - MARIADB_PORT_NUMBER=3306
      - REPORTSERVER_DATABASE_USER=bn_reportserver
      - REPORTSERVER_DATABASE_NAME=bitnami_reportserver
      - ALLOW_EMPTY_PASSWORD=yes
      - REPORTSERVER_INSTALLDEMODATA=no
    ports:
      - 8083:8080
      - 8084:8443
    depends_on:
      - rsmariadb

volumes:
  mariadb_data:
    driver: local
```
**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
